### PR TITLE
add icon for the macro kind

### PR DESCRIPTION
**Pull request by andreyorst**
Languages, which have macros, like Lisps, usually have a separate kind for them. For example, in Clojure with CIDER:

image.

With this change, an icon is added:

image

Suggestions on the icon, as well as the short name are welcome. I've chosen lambda, because, well, Lisp macros, I guess.

### CODE REVIEW

**Review by jdtsmith — CHANGES_REQUESTED** [review]
Thanks for this addition!  Do you think `font-lock-function-name-face` might be more appropriate?  Give it a try and let me know.  BTW, any other backends also providing this kind?  Perhaps Emacs-28 emacs-lisp?

**Comment by andreyorst** [comment]
All Lisps I know highlight macros with `font-lock-keyword-face` because macros and builtins are kinda indistinguishable from the user side.

**Comment by andreyorst** [comment]
> BTW, any other backends also providing this kind? Perhaps Emacs-28 emacs-lisp?

I don't remember exactly, and I'm not using LSP mode right now.

**Comment by jdtsmith** [comment]
Great thanks.

**Pull request merged**
